# Generated by Django 6.0.1 on 2026-01-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pasport',
            field=models.ImageField(blank=True, null=True, upload_to='users/students'),
        ),
    ]
