# Generated by Django 4.2.7 on 2026-02-11 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='attendance.organizationlocation'),
        ),
    ]
